#!/usr/bin/env node
/**
 * Andro Agent CLI — init / start / status / funnel
 */
import { randomBytes } from 'node:crypto'
import { existsSync, mkdirSync, readFileSync, writeFileSync, chmodSync } from 'node:fs'
import { homedir } from 'node:os'
import { join } from 'node:path'
import { spawnSync } from 'node:child_process'
import {
  CONFIG_DIR,
  ENV_PATH,
  TOKEN_PATH,
  loadEnvFile,
  detectMagicDns,
} from './config.js'

const BRAND = 'Andro Agent'
const CLI = 'andro-agent'

function printHelp(): void {
  console.log(`${BRAND} — local MCP agent for ChatGPT / Claude

Usage:
  ${CLI} init              Create token + ~/.config/browser-agent-mcp/env
  ${CLI} start             Start MCP server on :8787 (foreground)
  ${CLI} status            Health check + config summary
  ${CLI} funnel on         Publish /agent and /.well-known via Tailscale Funnel
  ${CLI} funnel off        Turn Funnel HTTPS off
  ${CLI} funnel status     Show Funnel status
  ${CLI} help              Show this help

Daily use after setup:  ${CLI} start
`)
}

function parseEnvFile(path: string): Record<string, string> {
  if (!existsSync(path)) return {}
  const out: Record<string, string> = {}
  for (const line of readFileSync(path, 'utf8').split('\n')) {
    const trimmed = line.trim()
    if (!trimmed || trimmed.startsWith('#')) continue
    const eq = trimmed.indexOf('=')
    if (eq <= 0) continue
    const key = trimmed.slice(0, eq).trim()
    let val = trimmed.slice(eq + 1).trim()
    if (
      (val.startsWith('"') && val.endsWith('"')) ||
      (val.startsWith("'") && val.endsWith("'"))
    ) {
      val = val.slice(1, -1)
    }
    out[key] = val
  }
  return out
}

function cmdInit(): void {
  mkdirSync(CONFIG_DIR, { recursive: true })

  let token: string
  if (existsSync(TOKEN_PATH)) {
    token = readFileSync(TOKEN_PATH, 'utf8').trim()
    console.log(`Token already exists: ${TOKEN_PATH}`)
  } else {
    token = randomBytes(32).toString('hex')
    writeFileSync(TOKEN_PATH, `${token}\n`, { mode: 0o600 })
    chmodSync(TOKEN_PATH, 0o600)
    console.log(`Created token: ${TOKEN_PATH}`)
  }

  const magicDns = detectMagicDns()
  const workspaceDefault = join(homedir(), 'Documents', 'GitHub')
  const workspace = process.env.WORKSPACE_ROOT?.trim() || workspaceDefault
  const port = process.env.PORT?.trim() || '8787'
  const host = process.env.HOST?.trim() || '127.0.0.1'

  const allowedHosts = magicDns
    ? `127.0.0.1,localhost,${magicDns}`
    : '127.0.0.1,localhost'
  const publicBase = magicDns
    ? `https://${magicDns}/agent`
    : `http://127.0.0.1:${port}/agent`
  const publicMcp = `${publicBase}/mcp`

  const envBody = `# ${BRAND} — generated by ${CLI} init
HOST=${host}
PORT=${port}
WORKSPACE_ROOT=${workspace}
MCP_AUTH_TOKEN=${token}
ALLOWED_HOSTS=${allowedHosts}
PUBLIC_BASE_URL=${publicBase}
PUBLIC_MCP_URL=${publicMcp}
BASH_TIMEOUT_MS=30000
`

  writeFileSync(ENV_PATH, envBody, { mode: 0o600 })
  chmodSync(ENV_PATH, 0o600)

  console.log(`Wrote env: ${ENV_PATH}`)
  if (magicDns) {
    console.log(`MagicDNS: ${magicDns}`)
  } else {
    console.log(
      'MagicDNS not detected (is Tailscale installed?). Edit PUBLIC_* in the env file after Funnel is up.',
    )
  }
  console.log('')
  console.log('Next:')
  console.log(`  1. ${CLI} funnel on`)
  console.log(`  2. ${CLI} start`)
  console.log('')
  console.log(`ChatGPT connector (OAuth): ${publicMcp}`)
  console.log(`Claude connector (Bearer):  ${publicMcp}`)
  console.log(`Activity UI (local):        http://${host}:${port}/activity`)
}

async function cmdStart(): Promise<void> {
  loadEnvFile()
  const { startServer } = await import('./server.js')
  startServer()
}

async function cmdStatus(): Promise<void> {
  loadEnvFile()
  const fileEnv = parseEnvFile(ENV_PATH)
  const port = Number.parseInt(
    process.env.PORT || fileEnv.PORT || '8787',
    10,
  )
  const host = process.env.HOST || fileEnv.HOST || '127.0.0.1'
  const publicMcp =
    process.env.PUBLIC_MCP_URL ||
    fileEnv.PUBLIC_MCP_URL ||
    '(not set — run andro-agent init)'
  const publicBase =
    process.env.PUBLIC_BASE_URL ||
    fileEnv.PUBLIC_BASE_URL ||
    '(not set)'

  console.log(`${BRAND} status`)
  console.log(`  config dir:  ${CONFIG_DIR}`)
  console.log(`  token:       ${existsSync(TOKEN_PATH) ? 'present' : 'MISSING'}`)
  console.log(`  env file:    ${existsSync(ENV_PATH) ? 'present' : 'MISSING'}`)
  console.log(`  public MCP:  ${publicMcp}`)
  console.log(`  public base: ${publicBase}`)

  const healthUrl = `http://${host}:${port}/healthz`
  try {
    const res = await fetch(healthUrl, { signal: AbortSignal.timeout(2000) })
    const body = (await res.json()) as Record<string, unknown>
    if (res.ok && body.ok) {
      console.log(`  health:      ok  (${healthUrl})`)
      console.log(`  workspace:   ${body.workspace ?? '?'}`)
      console.log(`  activity:    ${body.activity ?? '?'}`)
    } else {
      console.log(`  health:      unexpected response (${res.status})`)
      console.log(`  hint:        run \`${CLI} start\``)
    }
  } catch {
    console.log(`  health:      not running (${healthUrl})`)
    console.log(`  hint:        run \`${CLI} start\` then \`${CLI} funnel on\``)
  }
}

function runTailscale(args: string[]): number {
  const result = spawnSync('tailscale', args, {
    stdio: 'inherit',
    encoding: 'utf8',
  })
  if (result.error) {
    console.error(
      `Failed to run tailscale: ${result.error.message}\nIs Tailscale installed and on PATH?`,
    )
    return 1
  }
  return result.status ?? 1
}

function cmdFunnel(sub: string | undefined): number {
  loadEnvFile()
  const fileEnv = parseEnvFile(ENV_PATH)
  const port = fileEnv.PORT || process.env.PORT || '8787'
  const target = `http://127.0.0.1:${port}`
  const publicMcp =
    fileEnv.PUBLIC_MCP_URL ||
    process.env.PUBLIC_MCP_URL ||
    '(set PUBLIC_MCP_URL via andro-agent init)'

  switch (sub) {
    case 'on': {
      console.log(`${BRAND}: enabling Funnel for MCP (/agent + /.well-known) → ${target}`)
      const a = runTailscale([
        'funnel',
        '--bg',
        '--yes',
        '--set-path',
        '/agent',
        target,
      ])
      if (a !== 0) return a
      const b = runTailscale([
        'funnel',
        '--bg',
        '--yes',
        '--set-path',
        '/.well-known',
        target,
      ])
      if (b !== 0) return b
      console.log('')
      console.log(`ChatGPT / Claude MCP URL: ${publicMcp}`)
      console.log(`Verify with: ${CLI} funnel status`)
      return 0
    }
    case 'off': {
      console.log(`${BRAND}: turning Funnel HTTPS off`)
      return runTailscale(['funnel', '--https=443', 'off'])
    }
    case 'status':
    case undefined: {
      return runTailscale(['funnel', 'status'])
    }
    default:
      console.error(`Unknown funnel subcommand: ${sub}`)
      console.error(`Use: ${CLI} funnel on|off|status`)
      return 1
  }
}

async function main(): Promise<void> {
  const [cmd, sub] = process.argv.slice(2)
  switch (cmd) {
    case undefined:
    case 'help':
    case '--help':
    case '-h':
      printHelp()
      return
    case 'init':
      cmdInit()
      return
    case 'start':
      await cmdStart()
      return
    case 'status':
      await cmdStatus()
      return
    case 'funnel':
      process.exitCode = cmdFunnel(sub)
      return
    default:
      console.error(`Unknown command: ${cmd}\n`)
      printHelp()
      process.exitCode = 1
  }
}

main().catch((err) => {
  console.error(err instanceof Error ? err.message : err)
  process.exitCode = 1
})
